Rroutes leaderboard
norlab-ulaval/libpointmatcher-server pull request #61
Opened 2024-02-19 19:20 UTC by ThierryCrispin

Dites-moi si vous voyez autres chose à ajouter dans le model ` LeaderboardQuery`

2024-02-19 20:46 UTC, antoinegagnon9 requested changes

2024-02-19 20:46 UTC, antoinegagnon9 commented on api/interface/interface_models.py
> +    date: str
Check avec Caro il manque des infos je pense

2024-02-19 20:46 UTC, antoinegagnon9 commented on api/leaderboard/leaderboard_controller.py
> +    def get_leaderboard(self) -> Leaderboard:
Suggestion : Ajouter un champs "type" pour fetch le leaderboard spécifique à un type de score

2024-02-20 21:12 UTC, ThierryCrispin commented
J'ai ajouté un enum pour le type de score. Dites-moi ce que vous en pensez

2024-02-20 23:37 UTC, antoinegagnon9 approved these changes
Good pour moi
Je pense par contre que l'enum pourrait disparaître comme ça on aurait des types full dynamiques

2024-02-21 15:45 UTC, GabrielGagn0n approved these changes

2024-02-21 19:15 UTC, merged